language: node_js
node_js:
  - 18
  - 20

cache: false

before_install:
  - rm -rf node_modules
  - npm cache clean --force

install:
  - npm install

script:
  - npm run build
  - npm test -- --coverage --watchAll=false

branches:
  only:
    - main
    - test

notifications:
  email:
    on_success: change
    on_failure: always

